[package]
name = "day22"
version = "0.1.0"
authors = ["Tanel Liiv <tanel.liiv@defendec.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.2"
num = "0.2"
num-traits = "0.2"
primes = "0.2"
